//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazley_watch_boutique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> Userid { get; set; }
        public string productName { get; set; }
        public Nullable<int> productPrice { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Contact { get; set; }
    
        public virtual User User { get; set; }
    }
}
