//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazley_watch_boutique
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Carts = new HashSet<Cart>();
            this.Inquiries = new HashSet<Inquiry>();
        }
    
        public int productId { get; set; }
        public string model_no { get; set; }
        public string productName { get; set; }
        public string productImage { get; set; }
        public string collection { get; set; }
        public string brand { get; set; }
        public Nullable<decimal> price { get; set; }
        public string axis { get; set; }
        public string feature1 { get; set; }
        public string feature2 { get; set; }
        public string feature3 { get; set; }
        public string feature4 { get; set; }
        public Nullable<decimal> calibreId { get; set; }
        public string case_shape { get; set; }
        public string case_material { get; set; }
        public string case_size { get; set; }
        public string lug_width { get; set; }
        public string glass_material { get; set; }
        public string luminocity { get; set; }
        public string dial_color { get; set; }
        public string indexes { get; set; }
        public string strap_material { get; set; }
        public string strap_color { get; set; }
        public string clasp_type { get; set; }
        public string EAN { get; set; }
        public string gender { get; set; }
        public Nullable<int> water_resistence { get; set; }
        public string country_origin { get; set; }
        public string warrenty_period { get; set; }
        public string color { get; set; }
        public string material { get; set; }
        public string category { get; set; }
        public string size { get; set; }
        public string description { get; set; }
    
        public virtual brand brand1 { get; set; }
        public virtual calibre calibre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inquiry> Inquiries { get; set; }
    }
}
