//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazley_watch_boutique
{
    using System;
    using System.Collections.Generic;
    
    public partial class thewatchguide
    {
        public int Id { get; set; }
        public string image { get; set; }
        public string title { get; set; }
        public string writer { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string brand { get; set; }
        public string category { get; set; }
        public string description { get; set; }
    }
}
